### PR TITLE
Arm6 (and 8) export

### PR DESCRIPTION
**Pull request by tanyongkiam**
This updates the arm6/8 exporters and bootstraps a cross compiler from x64 to both targets.

### CODE REVIEW

**Comment by xrchz** [comment]
Can you update `build-sequence`?

**Comment by xrchz** [comment]
Also the naming conventions are inconsistent here. Observe that `compiler/bootstrap/compilation/riscv/riscvBootstrapTheory` produces a `riscv`-outputting compiler for `riscv`. But you've put an `arm6`-outputting compiler for `x64` in the analogous theory location for `arm6`.

**Comment by xrchz** [comment]
we figured some of this out on chat. pasting here:

`bootstrap/translation` culminates in two translations `compiler64Prog` and `compiler32Prog` - the first ends with a CF-verified `main` program for the CakeML compiler for all 64-bit out-targets, and the second is the same for arm6 as the out-target. N.B. the current `compiler64Prog` theory does not do this, but I suspect it should be extended in order to do so. Then delete the subdirectories of `translation`. Optionally replace the `32` and `64` suffixes on some of the `Prog` theories with subdirectories by those names instead.


for `bootstrap/compilation` the subdirectories look like `run-target/{32,64}/proofs`; within the 32/64 directory is a `runtargetBootstrap` theory that produces the compilation theorem (and outputs the `.S`)

**Comment by xrchz** [comment]
I won't run the regression while the requested updates above are still in progress.

**Comment by xrchz** [comment]
Regressions are now running automatically since this pull request is open. Is it actually wanting to be merged though?

**Comment by tanyongkiam** [comment]
I'll close the PR

**Comment by tanyongkiam** [comment]
I'm re-opening this because I probably can't run the bootstrap to completion on my machine (runs of of stack).

This implements the 64-bit version of #326 for x64. The riscv/arm8/mips versions can be similarly added if desired. It is unclear if the mips export script is actually correct.

Note that this includes PR #377 because I did not want to clash with that branch after it gets merged.

**Comment by xrchz** [comment]
What happens to the artefacts (tarballs containing bootstrapped compiler) after these changes? Do they have a new location?

**Comment by tanyongkiam** [comment]
I didn't test that, but I assumed it will be generated as usual by the Holmakefile here in this directory as cake-x64:
https://github.com/CakeML/cakeml/tree/arm6_export/compiler/bootstrap/compilation/x64/64

**Comment by xrchz** [comment]
Hmm, the symlinks there look incorrect - they probably need an extra `..` since they are one directory deeper now.

**Comment by xrchz** [comment]
Do you have `bootstrap/translation` in the build sequence twice?

**Pull request merged**
