### PR TITLE
Basis cleanup

### LINKED ISSUE #592: Remove Compare module & move its parts elsewhere
Currently, the `Compare` module in the basis consists of only:

```
Compare.bool_compare: bool -> bool -> ordering
Compare.num_compare: int -> int -> ordering
Compare.char_compare: char -> char -> ordering
Compare.list_compare: ('a -> 'b -> ordering) -> 'a list -> 'b list -> ordering
Compare.option_compare: ('a -> 'b -> ordering) -> 'a option -> 'b option -> ordering
Compare.option_cmp2: ('a -> 'b -> ordering) -> 'a option -> 'b option -> ordering
Compare.pair_compare: ('a -> 'b -> ordering) -> ('c -> 'd -> ordering) -> 'a * 'c -> 'b * 'd -> ordering
Compare.string_compare: char list -> char list -> ordering
```

This module ought to be deleted and most of its parts should be moved into other modules, e.g. `Compare.list_compare` should become `List.compare`. We might need a small new `Pair` module and possibly a `Bool` module.

The current `Compare.string_compare` seems wrong. I think it should become `String.compare: string -> string -> ordering`

### LINKED ISSUE #593: Tidy up Map module in basis
On a similar note, the `Map` module is a mess in the basis library: (1) it exposes all the internals, (2) it requires users to supply the comparison function at almost every function, (3) and the argument order in some cases is not ideal. Example:
```
Map.lookup: ('a -> 'b -> ordering) -> 'a -> ('b, 'c) balanced_map -> 'c option
```
I would much prefer it to be:
```
Map.lookup: ('a, 'b) map -> 'a -> 'b option
```
which can be achieved if `map` is a wrapper type that is `map = Map ('a -> 'b -> ordering) (('a, 'b) balanced_map)`, i.e. the idea is that the binary tree carries the relevant compare function. 

I suggest that the `balanced_mapTheory` in HOL is unchanged, but that a new wrapper theory is defined in `basis/pure/mlmapScript.sml` where the wrapping is done. 

Addressing (1) should be done after support for `local` exists in the translator, see #563.

### PR DESCRIPTION
**Pull request by myreen**
Once this is merged the basis has the following types. There are many things that could be improved, but I think this is good enough for now.

    Runtime.fullGC: unit -> unit
    Runtime.fail: unit -> unit
    Runtime.debugMsg: string -> unit
    Runtime.exit: int -> unit
    Runtime.abort: unit -> unit
    Option.getOpt: 'a option -> 'a -> 'a
    Option.isSome: 'a option -> bool
    Option.valOf: 'a option -> 'a
    Option.join: 'a option option -> 'a option
    Option.map: ('a -> 'b) -> 'a option -> 'b option
    Option.mapPartial: ('a -> 'b option) -> 'a option -> 'b option
    Option.compose: ('a -> 'b) -> ('c -> 'a option) -> 'c -> 'b option
    Option.composePartial: ('a -> 'b option) -> ('c -> 'a option) -> 'c -> 'b option
    Option.isNone: 'a option -> bool
    Option.map2: ('a -> 'b -> 'c) -> 'a option -> 'b option -> 'c option
    Option.compare: ('a -> 'b -> ordering) -> 'a option -> 'b option -> ordering
    List.null: 'a list -> bool
    List.length: 'a list -> int
    List.rev: 'a list -> 'a list
    List.@: 'a list -> 'a list -> 'a list
    List.hd: 'a list -> 'a
    List.tl: 'a list -> 'a list
    List.last: 'a list -> 'a
    List.getItem: 'a list -> ('a * 'a list) option
    List.nth: 'a list -> int -> 'a
    List.take: 'a list -> int -> 'a list
    List.drop: 'a list -> int -> 'a list
    List.takeUntil: ('a -> bool) -> 'a list -> 'a list
    List.dropUntil: ('a -> bool) -> 'a list -> 'a list
    List.cmp: ('a -> 'b -> ordering) -> 'a list -> 'b list -> ordering
    List.concat: 'a list list -> 'a list
    List.map: ('a -> 'b) -> 'a list -> 'b list
    List.mapi: (int -> 'a -> 'b) -> 'a list -> 'b list
    List.mapPartial: ('a -> 'b option) -> 'a list -> 'b list
    List.app: ('a -> 'b) -> 'a list -> unit
    List.find: ('a -> bool) -> 'a list -> 'a option
    List.filter: ('a -> bool) -> 'a list -> 'a list
    List.partition: ('a -> bool) -> 'a list -> 'a list * 'a list
    List.foldl: ('a -> 'b -> 'a) -> 'a -> 'b list -> 'a
    List.foldi: (int -> 'a -> 'b -> 'b) -> 'b -> 'a list -> 'b
    List.foldr: ('a -> 'b -> 'b) -> 'b -> 'a list -> 'b
    List.foldri: (int -> 'a -> 'b -> 'b) -> 'b -> 'a list -> 'b
    List.exists: ('a -> bool) -> 'a list -> bool
    List.all: ('a -> bool) -> 'a list -> bool
    List.snoc: 'a -> 'a list -> 'a list
    List.genlist: (int -> 'a) -> int -> 'a list
    List.tabulate: int -> (int -> 'a) -> 'a list
    List.collate: ('a -> 'b -> ordering) -> 'a list -> 'b list -> ordering
    List.zip: 'a list * 'b list -> ('a * 'b) list
    List.member: 'a -> 'a list -> bool
    List.sum: int list -> int
    List.unzip: ('a * 'b) list -> 'a list * 'b list
    List.pad_right: 'a -> int -> 'a list -> 'a list
    List.pad_left: 'a -> int -> 'a list -> 'a list
    List.all_distinct: 'a list -> bool
    List.isPrefix: 'a list -> 'a list -> bool
    List.front: 'a list -> 'a list
    List.splitAtPki: (int -> 'a -> bool) -> ('a list -> 'a list -> 'b) -> 'a list -> 'b
    List.update: 'a -> int -> 'a list -> 'a list
    List.compare: ('a -> 'b -> ordering) -> 'a list -> 'b list -> ordering
    List.sort: ('a -> 'a -> bool) -> 'a list -> 'a list
    Alist.lookup: ('a * 'b) list -> 'a -> 'b option
    Alist.update: ('a * 'b) list -> 'a * 'b -> ('a * 'b) list
    Alist.every: ('a * 'b -> bool) -> ('a * 'b) list -> bool
    Alist.map: ('a -> 'b) -> ('c * 'a) list -> ('c * 'b) list
    Alist.delete: ('a * 'b) list -> 'a -> ('a * 'b) list
    Vector.fromList: 'a list -> 'a Vector.vector
    Vector.length: 'a Vector.vector -> int
    Vector.sub: 'a Vector.vector -> int -> 'a
    Vector.tabulate: int -> (int -> 'a) -> 'a Vector.vector
    Vector.toList: 'a Vector.vector -> 'a list
    Vector.update: 'a Vector.vector -> int -> 'a -> 'a Vector.vector
    Vector.concat: 'a Vector.vector list -> 'a Vector.vector
    Vector.map: 'a Vector.vector -> ('a -> 'b) -> 'b Vector.vector
    Vector.mapi: 'a Vector.vector -> (int -> 'a -> 'b) -> 'b Vector.vector
    Vector.foldli: (int -> 'a -> 'b -> 'b) -> 'b -> 'a Vector.vector -> 'b
    Vector.foldl: ('a -> 'b -> 'a) -> 'a -> 'b Vector.vector -> 'a
    Vector.foldri: (int -> 'a -> 'b -> 'b) -> 'b -> 'a Vector.vector -> 'b
    Vector.foldr: ('a -> 'b -> 'b) -> 'b -> 'a Vector.vector -> 'b
    Vector.findi: (int -> 'a -> bool) -> 'a Vector.vector -> (int * 'a) option
    Vector.find: ('a -> bool) -> 'a Vector.vector -> 'a option
    Vector.exists: ('a -> bool) -> 'a Vector.vector -> bool
    Vector.all: ('a -> bool) -> 'a Vector.vector -> bool
    Vector.collate: ('a -> 'b -> ordering) -> 'a Vector.vector -> 'b Vector.vector -> ordering
    String.sub: string -> int -> char
    String.implode: char list -> string
    String.size: string -> int
    String.concat: string list -> string
    String.substring: string -> int -> int -> string
    String.strcat: string -> string -> string
    String.^: string -> string -> string
    String.explode: string -> char list
    String.extract: string -> int -> int option -> string
    String.concatWith: string -> string list -> string
    String.str: char -> string
    String.translate: (char -> char) -> string -> string
    String.split: (char -> bool) -> string -> string * string
    String.tokens: (char -> bool) -> string -> string list
    String.fields: (char -> bool) -> string -> string list
    String.isSubstring: string -> string -> bool
    String.isSuffix: string -> string -> bool
    String.isPrefix: string -> string -> bool
    String.compare: string -> string -> ordering
    String.<: string -> string -> bool
    String.<=: string -> string -> bool
    String.>=: string -> string -> bool
    String.>: string -> string -> bool
    String.collate: (char -> char -> ordering) -> string -> string -> ordering
    Bool.toString: bool -> string
    Bool.compare: bool -> bool -> ordering
    Pair.map: ('a -> 'b) -> ('c -> 'd) -> 'a * 'c -> 'b * 'd
    Pair.toString: ('a -> string) -> ('b -> string) -> 'a * 'b -> string
    Pair.compare: ('a -> 'b -> ordering) -> ('c -> 'd -> ordering) -> 'a * 'c -> 'b * 'd -> ordering
    Int.+: int -> int -> int
    Int.-: int -> int -> int
    Int.*: int -> int -> int
    Int.div: int -> int -> int
    Int.mod: int -> int -> int
    Int.<: int -> int -> bool
    Int.>: int -> int -> bool
    Int.<=: int -> int -> bool
    Int.>=: int -> int -> bool
    Int.~: int -> int
    Int.toString: int -> string
    Int.fromString: string -> int option
    Int.fromNatString: string -> int option
    Int.gcd: int -> int -> int
    Int.compare: int -> int -> ordering
    Rat.fromInt: int -> rat
    Rat.<=: rat -> rat -> bool
    Rat.>=: rat -> rat -> bool
    Rat.<: rat -> rat -> bool
    Rat.>: rat -> rat -> bool
    Rat.compare: rat -> rat -> ordering
    Rat.min: rat -> rat -> rat
    Rat.max: rat -> rat -> rat
    Rat.+: rat -> rat -> rat
    Rat.-: rat -> rat -> rat
    Rat.~: rat -> rat
    Rat.*: rat -> rat -> rat
    Rat.inv: rat -> rat
    Rat./: rat -> rat -> rat
    Rat.toString: rat -> string
    Char.ord: char -> int
    Char.chr: int -> char
    Char.<: char -> char -> bool
    Char.>: char -> char -> bool
    Char.<=: char -> char -> bool
    Char.>=: char -> char -> bool
    Char.isSpace: char -> bool
    Word64.fromInt: int -> Word64.word
    Word64.toInt: Word64.word -> int
    Word64.andb: Word64.word -> Word64.word -> Word64.word
    Word64.orb: Word64.word -> Word64.word -> Word64.word
    Word64.xorb: Word64.word -> Word64.word -> Word64.word
    Word64.notb: Word64.word -> Word64.word
    Word64.+: Word64.word -> Word64.word -> Word64.word
    Word64.-: Word64.word -> Word64.word -> Word64.word
    Word64.<<: Word64.word -> int -> Word64.word
    Word64.>>: Word64.word -> int -> Word64.word
    Word64.~>>: Word64.word -> int -> Word64.word
    Word8.fromInt: int -> Word8.word
    Word8.toInt: Word8.word -> int
    Word8.andb: Word8.word -> Word8.word -> Word8.word
    Word8.orb: Word8.word -> Word8.word -> Word8.word
    Word8.xorb: Word8.word -> Word8.word -> Word8.word
    Word8.notb: Word8.word -> Word8.word
    Word8.+: Word8.word -> Word8.word -> Word8.word
    Word8.-: Word8.word -> Word8.word -> Word8.word
    Word8.<<: Word8.word -> int -> Word8.word
    Word8.>>: Word8.word -> int -> Word8.word
    Word8.~>>: Word8.word -> int -> Word8.word
    Word8Array.array: int -> Word8.word -> byte_array
    Word8Array.sub: byte_array -> int -> Word8.word
    Word8Array.length: byte_array -> int
    Word8Array.update: byte_array -> int -> Word8.word -> unit
    Word8Array.copy: byte_array -> int -> int -> byte_array -> int -> unit
    Word8Array.copyVec: string -> int -> int -> byte_array -> int -> unit
    Word8Array.substring: byte_array -> int -> int -> string
    Array.array: int -> 'a -> 'a Array.array
    Array.arrayEmpty: unit -> 'a Array.array
    Array.sub: 'a Array.array -> int -> 'a
    Array.length: 'a Array.array -> int
    Array.update: 'a Array.array -> int -> 'a -> unit
    Array.fromList: 'a list -> 'a Array.array
    Array.tabulate: int -> (int -> 'a) -> 'a Array.array
    Array.copy: 'a Array.array -> 'a Array.array -> int -> unit
    Array.copyVec: 'a Vector.vector -> 'a Array.array -> int -> unit
    Array.app: ('a -> 'b) -> 'a Array.array -> unit
    Array.appi: (int -> int -> 'a) -> int Array.array -> unit
    Array.modify: ('a -> 'a) -> 'a Array.array -> unit
    Array.modifyi: (int -> 'a -> 'a) -> 'a Array.array -> unit
    Array.foldli: (int -> 'a -> 'b -> 'b) -> 'b -> 'a Array.array -> 'b
    Array.foldl: ('a -> 'b -> 'b) -> 'b -> 'a Array.array -> 'b
    Array.foldri: (int -> 'a -> 'b -> 'b) -> 'b -> 'a Array.array -> 'b
    Array.foldr: ('a -> 'b -> 'b) -> 'b -> 'a Array.array -> 'b
    Array.find: ('a -> bool) -> 'a Array.array -> 'a option
    Array.findi: (int -> 'a -> bool) -> 'a Array.array -> (int * 'a) option
    Array.exists: ('a -> bool) -> 'a Array.array -> bool
    Array.all: ('a -> bool) -> 'a Array.array -> bool
    Array.collate: ('a -> 'b -> ordering) -> 'a Array.array -> 'b Array.array -> ordering
    Map.lookup: ('a, 'b) map -> 'a -> 'b option
    Map.insert: ('a, 'b) map -> 'a -> 'b -> ('a, 'b) map
    Map.delete: ('a, 'b) map -> 'a -> ('a, 'b) map
    Map.null: ('a, 'b) map -> bool
    Map.empty: ('a -> 'a -> ordering) -> ('a, 'b) map
    Map.union: ('a, 'b) map -> ('a, 'b) map -> ('a, 'b) map
    Map.foldrWithKey: ('a -> 'b -> 'c -> 'c) -> 'c -> ('a, 'b) map -> 'c
    Map.map: ('a -> 'b) -> ('c, 'a) map -> ('c, 'b) map
    Map.toAscList: ('a, 'b) map -> ('a * 'b) list
    Map.fromList: ('a -> 'a -> ordering) -> ('a * 'b) list -> ('a, 'b) map
    Map.isSubmapBy: ('a -> 'b -> bool) -> ('c, 'a) map -> ('c, 'b) map -> bool
    Map.isSubmap: ('a, 'b) map -> ('a, 'b) map -> bool
    CommandLine.cline: unit -> string list
    CommandLine.name: unit -> string
    CommandLine.arguments: unit -> string list
    Marshalling.n2w2: int -> byte_array -> int -> unit
    Marshalling.w22n: byte_array -> int -> int
    TextIO.stdIn: TextIO.instream
    TextIO.stdOut: TextIO.outstream
    TextIO.stdErr: TextIO.outstream
    TextIO.output1: TextIO.outstream -> char -> unit
    TextIO.output: TextIO.outstream -> string -> unit
    TextIO.print: string -> unit
    TextIO.print_err: string -> unit
    TextIO.print_list: string list -> unit
    TextIO.openIn: string -> TextIO.instream
    TextIO.openOut: string -> TextIO.outstream
    TextIO.closeOut: TextIO.outstream -> unit
    TextIO.closeIn: TextIO.instream -> unit
    TextIO.input1: TextIO.instream -> char option
    TextIO.input: TextIO.instream -> byte_array -> int -> int -> int
    TextIO.inputLine: TextIO.instream -> string option
    TextIO.inputLines: TextIO.instream -> string list
    TextIO.inputLinesFrom: string -> string list option
    TextIO.inputAll: TextIO.instream -> string
    PrettyPrinter.fromString: string -> string app_list
    PrettyPrinter.fromChar: char -> string app_list
    PrettyPrinter.fromBool: bool -> string app_list
    PrettyPrinter.fromInt: int -> string app_list
    PrettyPrinter.fromNum: int -> string app_list
    PrettyPrinter.fromWord8: Word8.word -> string app_list
    PrettyPrinter.fromWord64: Word64.word -> string app_list
    PrettyPrinter.fromRat: int * int -> string app_list
    PrettyPrinter.fromOption: ('a -> string app_list) -> 'a option -> string app_list
    PrettyPrinter.fromPair: ('a -> string app_list) -> ('b -> string app_list) -> 'a * 'b -> string app_list
    PrettyPrinter.fromList: ('a -> string app_list) -> 'a list -> string app_list
    PrettyPrinter.fromArray: (string app_list -> string app_list) -> string app_list list -> string app_list
    PrettyPrinter.fromVector: (string app_list -> string app_list) -> string app_list list -> string app_list
    fst: 'a * 'b -> 'a
    snd: 'a * 'b -> 'b
    curry: ('a * 'b -> 'c) -> 'a -> 'b -> 'c
    uncurry: ('a -> 'b -> 'c) -> 'a * 'b -> 'c
    o: ('a -> 'b) -> ('c -> 'a) -> 'c -> 'b
    id: 'a -> 'a
    flip: ('a -> 'b -> 'c) -> 'b -> 'a -> 'c
    const: 'a -> 'b -> 'a
    update: 'a -> 'b -> ('a -> 'b) -> 'a -> 'b
    exp: int -> int -> int
    min: int -> int -> int
    max: int -> int -> int
    even: int -> bool
    odd: int -> bool
    funpow: ('a -> 'a) -> int -> 'a -> 'a
    abs_diff: int -> int -> int
    pre: int -> int
    while: ('a -> bool) -> ('a -> 'a) -> 'a -> 'a
    owhile: ('a -> bool) -> ('a -> 'a) -> 'a -> 'a option
    least: (int -> bool) -> int
    +: int -> int -> int
    -: int -> int -> int
    *: int -> int -> int
    div: int -> int -> int
    mod: int -> int -> int
    <: int -> int -> bool
    >: int -> int -> bool
    <=: int -> int -> bool
    >=: int -> int -> bool
    ~: int -> int
    @: 'a list -> 'a list -> 'a list
    =: 'a -> 'a -> bool
    not: bool -> bool
    <>: 'a -> 'a -> bool
    ^: string -> string -> string
    :=: 'a ref -> 'a -> unit
    !: 'a ref -> 'a
    print: string -> unit
    print_app_list: string app_list -> unit
    print_int: int -> unit

Closes #592 
Closes #593

### CODE REVIEW

**Comment by xrchz** [comment]
Are we going to promote camel case or snake case? (See pad right above, compared to most other multiword identifiers). This doesn't have to be decided for this PR. I think I prefer snake case even though SML chose camel.

**Comment by xrchz** [comment]
Re iocat, I'm fine to see it go, but I would like it to be possible to produce something as efficient using TextIO. If that's not possible eventually, I think the design is wrong.

**Comment by myreen** [comment]
I think I agree that it would be nicer to have snake case rather than camel case, e.g. `input_lines_from` rather than `inputLinesFrom`.

Re `TextIO`, one could arrive at something as efficient as `iocat` by adding two new functions to `TextIO`: one that takes an array as input and fills this array to some point with newly read data, another function that can print some subrange from a given array. Those would be fine new exposed functions. 

This PR is about ensuring all internal functions are hidden and the exposed ones have good types.

**Comment by xrchz** [comment]
There are a couple of [accessibility](https://stackoverflow.com/questions/1740116/for-what-reason-do-we-have-the-lower-case-with-underscores-naming-convention/1740152#1740152) [reasons](https://stackoverflow.com/questions/1740116/for-what-reason-do-we-have-the-lower-case-with-underscores-naming-convention/1740131#1740131) in favour of snake case. Many languages use both cases but for different namespaces (e.g., variables vs structures).

**Pull request merged**
