### PR TITLE
regenerate files with Lem 2018-07-13

### PR DESCRIPTION
**Pull request by larsrh**
Appears to only add type annotations. Let's see what the regression test thinks.

### CODE REVIEW

**Comment by xrchz** [comment]
It looks like this does break at least one proof in `primSemEnv`

**Comment by larsrh** [comment]
Is this a Lem regression? I'm having a hard time decoding the error message.

**Comment by larsrh** [comment]
This update is not of purely theoretical interest; I'm using this version of Lem to generate Isabelle and I'm interested in whether it still produces the same thing.

**Comment by xrchz** [comment]
I think the next failure is in `ml_translatorScript.sml`. Maybe @myreen can help. Re-open this when it's fixed.

**Comment by xrchz** [comment]
Is anyone working on this?

**Comment by xrchz** [comment]
@larsrh @SOwens any chance of updating CakeML for a new Lem version? Currently, I don't think there's any version of Lem that can redo the transformation from our `.lem` files to our `Script.sml` files.

**Comment by larsrh** [comment]
I can re-run Lem but I'm unable to fix the errors in the proofs.

**Comment by myreen** [comment]
Yong Kiam and I use the latest bitbucket version. That one seems to work
for generation of HOL4 scripts.

I know that Lem has moved to github, but the old one works for HOL4 as far
as I can tell.

**Comment by xrchz** [comment]
I didn't mean there's no version of Lem that can handle or `.lem` files. I meant there's no version that produces what we have checked in as `Script.sml` files. I would like there to be one and for its version number to be shown in the `README.md`. @larsrh is there any newer Lem than the one that produced the generated files already committed on this branch (`lem-updates`)?

**Comment by xrchz** [comment]
Actually, let me merge `master` into this branch first, because some updates may then be required anyway.

**Comment by talsewell** [comment]
I can have a look at fixing the translator, I'm feeling a bit under the weather, and maybe some braindead  work will help.

**Comment by talsewell** [comment]
I guess I'm doing this. I've got as far as getting the basis directory working.

**Comment by larsrh** [comment]
> is there any newer Lem than the one that produced the generated files already committed on this branch

I just checked and indeed, there is. So far I haven't updated my code to a later one, though. Let's wait and see how far @talsewell gets. I'd rather have this merged than update again and nothing merged.

**Comment by talsewell** [comment]
OK,  this now tests through to bootstrap/translation on my machine, will submit for a regression test.

**Comment by larsrh** [comment]
There's currently a merge conflict, which is probably the reason why the regression testing doesn't pick it up.

**Comment by xrchz** [comment]
The merge conflict is in a generated file. To resolve it, someone with the appropriate version of Lem should merge master into this branch, regenerate the file, then commit the result.

**Comment by larsrh** [comment]
I think this is an actual conflict. @mn200 committed 93e90787ca5eab690d73a51b5e6cdd99e53251fa, which touched some Lem-generated files. I'm unsure how to proceed, because re-generating these files will undo @mn200's legitimate changes.

**Comment by xrchz** [comment]
@larsrh are you happy with the current state of this pull request (as of e1321d9)?

**Comment by larsrh** [comment]
Has somebody rebased this? I haven't yet done what you suggested, but as usual, I don't want to let best be the enemy of good, so you have my approval.

**Comment by larsrh** [comment]
I'll submit a follow-up PR with a more recent version of Lem eventually. Thanks for merging this!

**Comment by myreen** [comment]
@larsrh the regression test failed on `oven2` which has an old Lem version installed (the one from bitbucket). The failure: https://cakeml.org/regression.cgi/job/650 

@xrchz was the PR merged a bit too eagerly? The PR seems to only have been tested only on a machine `oven1` that doesn't have Lem installed: https://cakeml.org/regression.cgi/job/647

Is there a Lem version that works with the current `master`? I tried the latest release of Lem, i.e. 2018-12-14, and 2018-07-13, but both fail when I try to build `make hol-libs` for Lem. `Holmake` complains about something to do with incorrect unicode. Here are the Lem releases: https://github.com/rems-project/lem/releases

**Comment by xrchz** [comment]
@larsh that's fine for most users, but we do want there to be a version of Lem that works and we want to test it.

**Comment by formrre** [comment]
2018-07-13 is unable to build `misc/lib.lem` on master, it can't find `List_extra` anymore, it looks like `libScript.sml` wasn't regenerated

**Pull request merged**
