### PR TITLE
Monadic trans

### PR DESCRIPTION
**Pull request by xrchz**
Generalise the monadic translator and pull it out as a separate library. Use it to translate the Candle kernel as before (but now with a CF hprop characterising the store invariant).

### CODE REVIEW

**Comment by xrchz** [comment]
@myreen you wanted to look at this?

**Comment by myreen** [comment]
@xrchz I'll have a look at it today. The commit messages sound very promising.

**Comment by myreen** [comment]
@xrchz The changes look fine by me and the code is neater than I had expected. I only have one stylistic remark regarding indentation:

    val store2heap_aux_Mem = Q.store_thm("store2heap_aux_Mem",
    `!s n x. x IN (store2heap_aux n s) ==> ?n' v. x = Mem n' v`,
    Induct_on `s`
     >-(rw[IN_DEF, store2heap_def, store2heap_aux_def]) >>
    rw[] >> fs[IN_DEF, store2heap_def, store2heap_aux_def] >>
    last_x_assum IMP_RES_TAC >>
    fs[]);

I would prefer if we kept indenting the way we have so far, i.e. 

    val store2heap_aux_Mem = Q.store_thm("store2heap_aux_Mem",
      `!s n x. x IN (store2heap_aux n s) ==> ?n' v. x = Mem n' v`,
      Induct_on `s`
       >-(rw[IN_DEF, store2heap_def, store2heap_aux_def]) >>
      rw[] >> fs[IN_DEF, store2heap_def, store2heap_aux_def] >>
      last_x_assum IMP_RES_TAC >>
      fs[]);

Nice work!

**Comment by xrchz** [comment]
@Kachoc see Magnus's comment above

**Pull request merged**
