### PR TITLE
Patch up broken proof in iocatProg (see comments)

### PR DESCRIPTION
**Pull request by oskarabrahamsson**
This is just a quick fix to get master building again.

The real issue here is that various rewrites and other things done
internally in cfLetAutoLib seems to depend on _when_ cfLetAutoLib
was loaded. When the Lib is loaded appears to have changed after a
recent update Holmake. This makes the xlet_auto heuristics instantiate
some variables in some theorems with the wrong things.

### CODE REVIEW

**Comment by mn200** [comment]
Libraries should not depend on load order at all, so the ideal fix would be to `cfLetAutoLib`...

**Comment by xrchz** [comment]
I agree with Michael. Why does the library depend on when it's loaded?

**Comment by xrchz** [comment]
I see there is issue #699 to address that, so this pull request can go ahead when it passed. Thanks Oskar!

**Comment by oskarabrahamsson** [comment]
I also agree. Until whatever is up with `cfLetAutoLib` is fixed it would be nice if a few PRs could build, though.

I wrote an issue about this: #699. `cfLetAutoLib` picks out `srw_ss` at some point in time. The tactic succeeds or fails with various goals depending on what's in the simpset at the time when the library is loaded. I have no idea how it works so I can't say what simplifications it should know about.

**Comment by myreen** [comment]
The regression test failed, but this is an improvement on master so I will merge it.

**Pull request merged**
