### PR TITLE
Prove some stronger results about GC algorithm

### PR DESCRIPTION
**Pull request by myreen**

### CODE REVIEW

**Comment by myreen** [comment]
I've checked that all of the compiler proofs succeed. This PR only touches the compiler proofs, so I'm merging this PR.

**Comment by xrchz** [comment]
The compiler proofs also affect the bootstrap proofs (this is why #498 is not merged)

**Comment by myreen** [comment]
#498 changed the basis which affects the translator and the CF proofs, so this is clearly affecting the bootstrap.

In contrast, the additions to the GC proofs in this PR are completely internal to the proofs of `data_to_word` and do not even affect the top-level proofs of the `data_to_word` compiler. I can’t see how these could break anything later. (I also didn’t introduce any new automatic rewrites.)

**Comment by xrchz** [comment]
Ok that makes sense :)

**Pull request merged**
