### PR TITLE
Constant folding and propagation in word_simp

### PR DESCRIPTION
**Pull request by myreen**
This is @AndreasLoow's optimisation for `wordLang`. This optimisation pushes constants forward and performs simple constant folding. The optimisation is able to push constants past `Call`, if the call does not have an exception handler.

### CODE REVIEW

**Comment by AndreasLoow** [comment]
We can probably close #129 when this is merged.

**Comment by xrchz** [comment]
Trying to build this failed in the bootstrap translation:
```to_word64ProgTheory                                                     FAILED!
 Translating word_simp_apply_if_opt
 Saved theorem _____ "word_simp_apply_if_opt_v_thm"
 Translating word_simp_simp_if
 Translating word_simp_const_fp_move_cs
 error in quse /home/ramana/cakeml5/compiler/bootstrap/translation/to_word64ProgScript.sml : UnsupportedType ?
 error in load to_word64ProgScript : UnsupportedType ?
 Failed translation: const_fp_inst_cs
 Failed translation: const_fp_loop
 Failed translation: const_fp
 Failed translation: compile_exp
```

If I find time I'll look into it, but anyone else can feel free to fix too.

**Comment by xrchz** [comment]
@tanyongkiam I think this might require some of your expertise

**Comment by tanyongkiam** [comment]
It looks like an uninstantiated (word) type variable. I've left it building in the background.

**Pull request merged**
