### PR TITLE
Include commit hash in bootstrapped compiler

### PR DESCRIPTION
**Pull request by oskarabrahamsson**
This pull request addresses #373. 

A `--version` flag is added to the bootstrapped compiler binary, which shows the following (when available) before terminating.

* Build date
* The CakeML commit hash
* The HOL4 commit hash
* PolyML version

### CODE REVIEW

**Comment by oskarabrahamsson** [comment]
I added some functionality to preamble:

```sml
(* tm_from_proc cmd args *)
val tm_from_proc : string * string list -> term

(* tm_from_proc_from dir cmd args *)
val tm_from_proc_from : string * string * string list -> term

(* mlstring_from_proc dir cmd args *)
val mlstring_from_proc : string * string list -> term

(* mlstring_from_proc_from dir cmd args *)
val mlstring_from_proc_from : string * string * string list -> term
```

These all execute an external process and capture its standard output as string or mlstring terms. Optionally a working directory for the process can be specified with `xxx_from_proc_from`.

**Comment by xrchz** [comment]
As you can see, the regression test failed.

**Comment by xrchz** [comment]
Reopen when the failure has been addressed

**Comment by oskarabrahamsson** [comment]
I ran the x64 bootstrap compilation myself this time. In addition to fixing the previous regression test failure, the `--version` flag is checked in the ML wrapper around the `compile_to_bytes` function (this is the only way to avoid reading input from `stdin`).

**Comment by oskarabrahamsson** [comment]
Closing this as it is included in #352.

**Pull request closed without merging**
