### PR TITLE
Resuscitate presLang as to_displayLang

### PR DESCRIPTION
**Pull request by talsewell**
RFC at this stage. This is a first step towards resurrecting the
explorer (or some of it): rebuild the conversions from the various
ILs to the printable displayLang form.

The theory runs, but I don't know how to test whether there's
any risk of breaking anything else (e.g. translation).

### CODE REVIEW

**Comment by talsewell** [comment]
Curiously, git hasn't figured out the files are related. I wonder if I should try
to adjust the edit so it does, so as to preserve the history to the real authors.

**Comment by xrchz** [comment]
The regression test indicates that it did break something else in the compiler proofs.

**Comment by xrchz** [comment]
We usually use open PRs for things that are ready to merge as soon as the regression test succeeds -- I don't think this is currently in that state, is it? It's possible this policy should change since PRs are nice for discussion. (The regression test server would need to be configured to pay more attention to labels or something other than just the PR open/closed state.)

**Comment by xrchz** [comment]
> We usually use open PRs for things that are ready to merge as soon as the regression test succeeds -- I don't think this is currently in that state, is it? It's possible this policy should change since PRs are nice for discussion. (The regression test server would need to be configured to pay more attention to labels or something other than just the PR open/closed state.)

Note that this https://platform.github.community/t/negate-a-filter-find-prs-without-a-certain-label/6967 makes the above non-trivial. I'd be happy for someone else to think about a good way to change the server, though.

**Comment by IlmariReissumies** [comment]
Or we could say that discussions on things that are not ready for prime time should go not on pull requests but on the issue that's being worked on.

**Comment by xrchz** [comment]
> Or we could say that discussions on things that are not ready for prime time should go not on pull requests but on the issue that's being worked on.

Oh yes, that's a good norm too -- I had forgotten about issue discussions :)

**Comment by lorenzleutgeb** [comment]
IMO Issues are fine for keeping track and discussing ideas and matters that are bigger/more abstract than code (or might not even result in code being produced). Also one issue might be associated with multiple PRs and have a longer lifetime. As soon as there actually is code to be discussed, a PR offers a better set of features (reviews that can be requested and then result in rejection/approval, comments on specific lines that expand into threads, integration with other checking services like Travis CI, ...). By closing issues for the sake of controlling the regression server, this "workflow" is disturbed a lot.

**Comment by talsewell** [comment]
@xrchz OK, I'm happy to do things differently. In my first week I didn't have a clue how to run the regression test, or where to run it without breaking other things, so it was convenient to have the PR worker do it for me. Also, I would actually like to merge this? Should I go back and edit my leading comment? I'd clean the history first, and address any actual requests/complaints/preferences.

**Comment by xrchz** [comment]
No need to edit the comments/discussion, but to get this merged it'll need to pass the regression test at least.

**Comment by talsewell** [comment]
Well, yeah. I kind of hoped the last run would succeed. The partiality of translation is the problem here, and I have no experience in fixing it, but we'll get there.

**Comment by talsewell** [comment]
More work to be done. I'm going to close this here to stop the regression worker wasting time, and reopen in the standard CakeML workflow.

**Pull request closed without merging**
