### PR TITLE
Clos stub

### PR DESCRIPTION
**Pull request by SOwens**
This reduces the amount of stub code that clos_to_bvl needs to generate. But it is still quadratic in max_app.

### CODE REVIEW

**Comment by xrchz** [comment]
It's not clear any more what, if anything, should be merged, since more commits are coming in with partial progress. Would it be possible to either create a new branch for more commits (and leave this one where you want the merge to happen), or wait until all this is finished before merging?

**Comment by myreen** [comment]
I chatted with Scott yesterday and got the impression that he wants it to
merge often into master. I talked about creating a new branch for the next
phase of improvements. However, I suspect he forgot to create the new
branch. I believe the commit ae24c95 is where he intended the merge.

**Comment by SOwens** [comment]
What Magnus writes is all correct.

I thought the point of the pull request is that it picks out a commit that you want merged, and then the tests can be started and eventually it will be committed. Given that the tests take 2 days, I don’t think it’s surprising that development will continue in the mean time.

Scott

**Comment by xrchz** [comment]
We are in agreement about it being desirable to pick a "checkpoint" to test and merge, and to want to continue development in the meantime. The problem is technical, in how pull requests are implemented on GitHub. They don't pick a commit, they follow a branch. In particular, at the bottom of the pull request it says "Add more commits by pushing to the clos_stub branch". So, continued development needs to happen on a different branch (or, the checkpoint pull request needs to be given a different branch). Shall I make a branch at ae24c95, close this pull request, and open a new one on that branch? (The other obvious approach is to make a new branch for continued development and push clos_stub back to ae24c95.)

**Comment by SOwens** [comment]
I didn’t realise that was how github worked. The best plan here is to make a new branch for ae24c95, and make the pull request from that, not mess with clos_stub, and allow development to continue from that.

Scott

**Comment by xrchz** [comment]
OK, closing this pr (can be reopened when clos_stub is done) and making a new one for the checkpoint.

**Pull request closed without merging**
