### PR TITLE
Fileioffi

### PR DESCRIPTION
**Pull request by hferee**

### CODE REVIEW

**Comment by xrchz** [comment]
I think the `ltemporal` and `optionMonad` theories should simply be added to HOL, probably merged into `llist` and `option`. You could put them into `misc` for the time being.

**Comment by hferee** [comment]
Do you mean the misc Script or directory?

**Comment by xrchz** [comment]
I mean `miscTheory`.

**Comment by xrchz** [comment]
This is failing the regression test rather early (in `basis`)

**Comment by hferee** [comment]
I'm running the regression test on a fresh install and it went through basis with no issue (although it might fail later).

**Comment by hferee** [comment]
However, it fails in `compiler/backend/gc` because of an overloaded notation. I'll fix it and re-run the regression test before pushing.

**Comment by hferee** [comment]
This should be fine now.

**Comment by xrchz** [comment]
I expect it will still fail on basis: what needs to be tested is not this branch as it is, but its merger with master (since that's what the new master will become).

**Pull request merged**
