### PR TITLE
ArgParse for CakeML

### PR DESCRIPTION
**Pull request by agomezl**
This is a relatively simple library for parsing arguments using a declarative interface for specifying which kind of argument/options to take. the following example shows a simple use case.

Assume a program `foo` with the following arguments
```
Usage foo
  -f  --input     Input file to use
  -o  --output    Output file
  -h  --help      This message
```
We use a datatype to represent the configuration of `foo`
```
val _ = Datatype`
  foo_opt = <| input  : mlstring option;
               output : mlstring option;
               help   : bool|>
`;
```

and write a configuration using the `flag` datatype

```sml
val foo_conf_def = Define`
  foo_conf = mkArgsConf [(* -i --input *)
                         <| name  := implode "input";
                            short := #"i";
                            desc  := implode "Input file to use";
                            has_option := T; (* It spects an option *)
                            cont := (λarg conf. conf with <|input := arg|>) |>;
                         (* -o --output  *)
                         <| name  := implode "output";
                            short := #"o";
                            desc  := implode "Output file";
                            has_option := T;
                            cont := (λarg conf. conf with <|input := arg|>) |>;
                         (* -h --help *)
                         <| name  := implode "help";
                            short := #"h";
                            desc  := implode "This message";
                            has_option := F;
                            cont := K (λconf. conf with <|help := T|>)|>
                        ]
                  (* Default configuration *)
                  <|input  := NONE;
                    output := NONE;
                    help   := F
                   |>
`;
```

and then

```
> EVAL ``parse_conf foo_conf (MAP implode ["--input"])``;
val it =
   ⊢ parse_conf foo_conf (MAP implode ["--input"]) =
       INL (strlit "Missing value to: --input"): thm

> EVAL ``parse_conf foo_conf (MAP implode ["--input";"text.txt"])``;
val it =
   ⊢ parse_conf foo_conf (MAP implode ["--input"; "text.txt"]) =
       INR <|input := SOME (strlit "text.txt"); output := NONE; help := F|>:
   thm

> EVAL ``parse_conf foo_conf (MAP implode ["--input=in.txt";"--output";"out.txt"])``;
val it =
   ⊢ parse_conf foo_conf (MAP implode ["--input=text.txt"; "--output"; "out.txt"]) =
       INR <|input := SOME (strlit "out.txt"); output := NONE; help := F|>:
   thm
```
This is just the core functionality since there are still some quality of life components  missing (help message generation, helper functions, etc).

### CODE REVIEW

**Comment by xrchz** [comment]
Somehow this breaks `compilerTheory` - can you fix?

**Comment by xrchz** [comment]
I think this breaks `grepProg` somehow

**Comment by xrchz** [comment]
Reopen when fixed

**Comment by agomezl** [comment]
Fixed the issues with `grepProg` and some other down the line with `parseProg`

**Comment by xrchz** [comment]
Now breaks with something to do with the article reader

**Comment by agomezl** [comment]
Ok, I rebasing and fixing that

**Comment by agomezl** [comment]
@oskarabrahamsson fixed the problem with the article reader!

**Comment by xrchz** [comment]
This may be timing out in `translator/other-examples` -- either that or `Holmake` has died silently...

**Comment by agomezl** [comment]
It did't actually failed, but I some how I messed up the job. How can I trigger a rebuild?

**Comment by agomezl** [comment]
This is getting stuck in `compiler/inference/test` I'm currently looking at what is happening

**Comment by xrchz** [comment]
Did you find anything out about that?

**Comment by agomezl** [comment]
This bit is the one looping:

https://github.com/CakeML/cakeml/blob/cc95061c249ee1e7010fa61ef0171faa133fc739/compiler/inference/tests/basisTypeCheckScript.sml#L20

I honestly don't know what is happening there, I will ask around tomorrow (today I was rebasing and building the whole thing)

**Comment by agomezl** [comment]
Rebased to fix conflict

**Comment by xrchz** [comment]
Maybe there's something in what you added that needs to go in one of the compsets for evaluation.

**Comment by xrchz** [comment]
To make progress on this, I think someone needs to do binary search on prefixes of the basis to see where the inferencer goes into a loop.

**Comment by agomezl** [comment]
Running `val test = inf_eval "infertype_prog init_config (TAKE 73 basis)"` works just fine, but anything more than that hangs, `EVAL "EL 73"` gives:

```
val it =
  ⊢ EL 73 basis =
    Dmod "Map"
      [Dlet
         (Locs <|row := 0; col := 0; offset := 0|>
            <|row := 0; col := 0; offset := 0|>) (Pvar "size")
         (Fun "v6"
            (Mat (Var (Short "v6"))
               [(Pcon (SOME (Short "Tip")) [],Lit (IntLit 0));
                (Pcon (SOME (Short "Bin"))
                   [Pvar "v5"; Pvar "v4"; Pvar "v3"; Pvar "v2"; Pvar "v1"],
                 Var (Short "v5"))]));
       Dlet
         (Locs <|row := 0; col := 0; offset := 0|>
            <|row := 0; col := 0; offset := 0|>) (Pvar "singleton")
         (Fun "v1"
...(etc)...
```

**Comment by agomezl** [comment]
Doing some more digging, `TAKE 74 basis` looks the same both in `master` and `argparse` (after merging) so the ast hasn't change, but doing a diff on the compsets being used  (`computeLib.listItems cmp`) gives me:

```
$ colordiff cake_argparse/computeLib.log cake_master/computeLib.log
687,688c687,688
<     (("Asub", "ast"), []), (("Atapp", "ast"), []), (("Atfun", "ast"), []),
<     (("Attup", "ast"), []), (("Atvar", "ast"), []), (("Aupdate", "ast"), []),
---
>     (("Asub", "ast"), []), (("Atapp", "ast"), []), (("Attup", "ast"), []),
>     (("Atvar", "ast"), []), (("Aupdate", "ast"), []),
880,881c880,884
<     (("EVEN", "arithmetic"), [RRules [? ?n. EVEN (BIT1 n) ? F, ...]]),
<     (("EVERY", "list"), [...]), ...]:
---
>     (("EVEN", "arithmetic"),
>      [RRules [? ?n. EVEN (BIT1 n) ? F, ? ?n. EVEN (BIT2 n) ? T, ...]]),
>     (("EVERY", "list"),
>      [RRules [? ?t h P. EVERY P (h::t) ? P h ? EVERY P t, ...]]),
>     (("EXISTS", "list"), [...]), ...]:
```
so `EXISTS` got removed from the compset somehow in the `argparse` branch which might be an indication that something went wrong at some point.

**Comment by xrchz** [comment]
I'm closing this for now -- please reopen when fixed.

**Comment by myreen** [comment]
I'm temporarily closing this since its current state causes the regression test to get stuck.

**Comment by xrchz** [comment]
Do we know what's wrong?

**Pull request closed without merging**
