### PR TITLE
Removes asm_ok checks for non-jump instructions

### PR DESCRIPTION
**Pull request by tanyongkiam**
All of backend/proof and benchmarks/ build.

(as a side effect, this also made wordLang and below support Div instructions)

Things that still need to be done:
1) Update the unverified register allocator to account for forced edges (currently unused)
2) Fix the two cheats in configProof

### CODE REVIEW

**Comment by xrchz** [comment]
Regression test for this merge is running on Bamboo.

**Comment by tanyongkiam** [comment]
I guess it probably passed and got stuck in bootstrap. If so, hold on to the merge because I am fixing the configProof cheats mentioned in the PR.

**Comment by xrchz** [comment]
Preliminary tests suggest this might be a problem:
```
to_word64ProgTheory                                                     FAILED!
 Translating word_alloc_remove_dead
 Adding type :clash_tree
 Saved definition __ "REG_ALLOC_CLASH_TREE_TYPE_def"
 Saved theorem _____ "REG_ALLOC_CLASH_TREE_TYPE_def"
 Case translation: 4 3 2 1 done.
 Adding type :α asm_config
 Adding type :α asm
 error in quse /home/ramana/cakeml4/compiler/bootstrap/translation/to_word64ProgScript.sml : HOL_ERR {message = "For :\206\177 word\n\nException raised at TypeBasePure.case_def_of:\n\"fcp$cart\" is not a datatype\n", origin_function = "type_of_cases_const", origin_structure = "HolKernel"}
 error in load to_word64ProgScript : HOL_ERR {message = "For :\206\177 word\n\nException raised at TypeBasePure.case_def_of:\n\"fcp$cart\" is not a datatype\n", origin_function = "type_of_cases_const", origin_structure = "HolKernel"}
 Failed translation: word_alloc
```

**Comment by xrchz** [comment]
(I'll have a look and fix it if it's easy.)

**Comment by xrchz** [comment]
It fails on translation of `get_forced`,  and it has something to do with type instantiation probably, but I can't figure it out easily.

**Comment by tanyongkiam** [comment]
This is now fixed, and the rest of the translation builds for me.

**Comment by xrchz** [comment]
There may be a performance regression (or infinite loop even) in `bootstrap/evaluation`, but I think this can be addressed on master..

**Pull request merged**
