### PR TITLE
Haskell constructors

### PR DESCRIPTION
**Pull request by mn200**
I think this is ready for merge.  Soundness and completeness proofs have been fixed.

### CODE REVIEW

**Comment by xrchz** [comment]
I'm running a regression on it.

**Comment by mn200** [comment]
The `basis` directory builds successfully on my machine as of 1245d9a

**Comment by xrchz** [comment]
Is this replaced by the `haskell-datatype-decl` branch? I think this branch shouldn't be merged because it breaks `characteristic/examples` (due to `ref`) but maybe that's being fixed on the other branch.

**Comment by mn200** [comment]
Yes.  I'll fast forward this branch to be the same as the other to make things easier though.

**Comment by mn200** [comment]
Latest Bamboo regression looks to be timing out in `characteristic/examples/compilation/proofs` in the same way as happened on master.

**Pull request merged**
