### PR TITLE
Issue159

### LINKED ISSUE #159: Replace FFI indexes with FFI names
FFI calls currently take a number which indicates which external function is to be called. The numbers are convenient for the compiler, but inconvenient for all other purposes. 

I suggest we replace FFI indexes (num) with FFI names (string). This way one can avoid magic numbers, i.e. have the compiler pick the numbers. Reasoning and modelling FFI behaviour will also be a bit more convenient once we have names instead of numbers.

### PR DESCRIPTION
**Pull request by IlmariReissumies**
Make FFI calls use names, rather than numbers, to refer to external functions.

My hope is that with these changes we can close #159.

### CODE REVIEW

**Comment by xrchz** [comment]
Regression test is in progress.

**Comment by xrchz** [comment]
```
x64BootstrapTheory                                                      FAILED!
 /root/remote-agent/xml-data/build-dir/CML-RT19-BC/cakeml/compiler/bootstrap/evaluation/x64BootstrapScript.sml:205: warning: Matches are not exhaustive.
 Found near
   fun
      compute_labels_alt_conv _ [...] ... = REWR_CONV cln tm |
         compute_labels_alt_conv n ... = tm |> (... THENC ...)
          compute_labels eval: runtime: 1h21m42s,    gctime: 29m34s,     systime: 41.7s.
          compute_labels real: 1h22m23s
          compute_labels size: 980950
          enc_secs_again eval: error in quse /root/remote-agent/xml-data/build-dir/CML-RT19-BC/cakeml/compiler/bootstrap/evaluation/x64BootstrapScript.sml : HOL_ERR {message = "REWR_CONV: lhs of thm doesn't match term", origin_function = "RAND_CONV", origin_structure = "Conv"}
 error in load x64BootstrapScript : HOL_ERR {message = "REWR_CONV: lhs of thm doesn't match term", origin_function = "RAND_CONV", origin_structure = "Conv"}
```

**Comment by xrchz** [comment]
It's possible that I should be looking at this, or that it waits for the `labels-tail-rec` branch...

**Comment by xrchz** [comment]
I'm looking at resolving the conflicts.

**Comment by IlmariReissumies** [comment]
Thank you!

**Pull request merged**
